# Generated by Django 4.1.1 on 2022-09-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencer_api', '0002_sequence_date_sequence_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='date',
        ),
    ]
