# Generated by Django 4.1.1 on 2022-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencer_api', '0003_remove_sequence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='steps',
            field=models.IntegerField(null=True),
        ),
    ]
